Work from home
techchapter/techchapter.fyi pull request #9
Opened 2024-10-14 08:18 UTC by rorbol

2024-10-21 06:37 UTC, nanohest requested changes
spelling is hard

2024-10-21 06:37 UTC, nanohest commented on hjemmearbejde.md
> +Det forventes at alle medarbejdere arbejder fra kontoret i åbningstiden (9:30-15:30) når det er muligt og mindst en dag ugenligt fastlagt af Tech Chapter. Formålet er at styrke det faglige og sociale
```suggestion
Det forventes at alle medarbejdere arbejder fra kontoret i åbningstiden (9:30-15:30) når det er muligt og mindst en dag ugenligt fastlagt af Tech Chapter. Formålet er at styrke det faglige og sociale fællesskab i Tech Chapter - ikke kun for dig, men også for dine kollegaer. Samtidig at skabe et attraktivt kontormiljø og at lette vidensdeling om små og store emner. Enddelig skal kontoret bemandes for at kunne modtage besøgende, varer og passe telefonen.
```

2024-10-21 06:37 UTC, nanohest commented on hjemmearbejde.md
> +Flere har opgaver det kræver tilstedeværelse hos kunder. Vi bestræber os på at holde dette på højst 3 dage ugenligt, men der kan være untagelser herfor. Prøv gerne at aftale faste mødedage med kunden
```suggestion
Flere har opgaver det kræver tilstedeværelse hos kunder. Vi bestræber os på at holde dette på højst 3 dage ugentligt, men der kan være undtagelser herfor. Prøv gerne at aftale faste mødedage med kunden, i den udstrækning dette er muligt.
```

2024-10-21 06:37 UTC, nanohest commented on salery.md
> +- Når årets resultat foreligger beslutter aktionærer hvilket beløb, der skal udlodes.
```suggestion
- Når årets resultat foreligger beslutter aktionærerne hvilket beløb, der skal udloddes.
```

2024-10-21 06:37 UTC, nanohest commented on salery.md
> +- Overskudet vægtes efter de måneder, konsulenten har arbejdet mindst halvdelen af mulige arbejdsdage. Ferie medregenes, orlov meregnes ikke.
```suggestion
- Overskudet vægtes efter de måneder, konsulenten har arbejdet mindst halvdelen af mulige arbejdsdage. Ferie medregenes, orlov medregnes ikke. 
```

2024-10-21 06:37 UTC, nanohest commented on salery.md
> +Derudover tilbyder vi en række goder, herunder choose-you-own-device(s), 12 ugers betalt barsel, fleksibel feriepolitik, firmakreditkort, sundheds- og tandforsikring, medarbejder telefon og internet,
```suggestion
Derudover tilbyder vi en række goder, herunder choose-your-own-device(s), 12 ugers betalt barsel, fleksibel feriepolitik, firmakreditkort, sundheds- og tandforsikring, medarbejder telefon og internet, frokostordning, mulighed for firmabil, pendlerkort, med videre.
```

2024-10-23 09:43 UTC, nanohest approved these changes

2024-10-25 08:37 UTC, jesstruck approved these changes

2024-10-25 08:38 UTC, merged